# Generated by Django 4.0.4 on 2022-05-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discountedPrice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/product'),
        ),
    ]
